version: "3.7"
services:
    notebook-server:
        build: 
            context: .
            dockerfile: Dockerfile
        shm_size: '10.24gb'
        environment:
            - JUPYTER_TOKEN=password
        volumes: 
            - ./data:/app/data
            - ./notebooks:/app/notebooks
            - ./logs:/app/logs
            - ./requirements:/app/requirements
            - ./scripts:/app/scripts
        ports:
            # Jupyter port
            - "8888:8888"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
